# AJura By: killeratnight
#
# Put Description Here that explains this
# plugin
#
# The Commands list is the list where you can add custom commands you want the plugin
# to run with the assigned wurd
# e.g - Banana wurd will "RunCmd" the command named 'WarnCommand'
#
# Adding a command is as simple as copying one of the already available commands and pasting
# it in the list followed by renaming it and changing the command it will run
# @player will be replaced with the player's name.
#
# Enabled - Pretty self explanatory, determines whether the plugin is enabled or not.
# MaxStrikes - When a player mentions one of the listed wurds in BadWurds, they get a strike added to their
#              record, this is the threshold number of strikes before the player gets a punishment.
# StrikePunishment - The command that will run when the player has reach the maximum strikes assigned.
#
# BadWurds - The list where you add the foul wurds that you wish to flag.
# The BadWurds list has prioritization, simply rearrange the words with their priority
# e.g - Banana comes first before Lag, so the plugin will check for Banana in the player's message
#       before Lag and so on..
#
# Flags:
#  ReplaceWith: 'NewWurdHere' - Replace the BadWurd with this wurd.
#  CancelMsg: boolean - Set True/False to cancel the chat message.
#  RunCmd: 'CommandHere' - Run Specified command from "Commands" list.
#
#
Enabled: true
MaxStrikes: 3
StrikePunishment: '/tempban @player 1d'
Commands:
  MuteCommand: '/mute @player 20m'
  WarnCommand: '/tell @player you have been warned'
  KickCommand: '/kick @player No Saying Bad Wurds'
  TempBanCommand: '/tempban @player 10m'

BadWurds:
  Banana:
    ReplaceWith: 'chow'
    RunCmd: 'WarnCommand'
  Lag:
    RunCmd: 'MuteCommand'
    CancelMsg: true
  Ching:
    RunCmd: 'KickCommand'
  Fricker:
    RunCmd: 'WarnCommand'
    ReplaceWith: 'Turtles'